services:
  - type: web
    name: student-room-finder-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: CLOUDINARY_NAME
        scope: build
      - key: CLOUDINARY_API_KEY
        scope: build
      - key: CLOUDINARY_API_SECRET
        scope: build
      - key: NODE_ENV
        value: production
        scope: build
